# -*- mode: ruby -*-
# vi: set ft=ruby :

box = "ubuntu/wily64"


Vagrant.configure(2) do |config|

  config.vm.box = box
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.synced_folder "webapp", "/home/isucon/webapp/go", owner: "isucon", group: "isucon"
  config.vm.synced_folder "html", "/home/isucon/html", owner: "isucon", group: "isucon"
  config.vm.synced_folder "sql", "/home/isucon/sql", owner: "isucon", group: "isucon"
  config.vm.synced_folder "scripts", "/home/isucon/scripts", owner: "isucon", group: "isucon"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "isucon4-qualifier"
    vb.memory = "4096"
    vb.cpus = "4"
  end

  config.vm.provision "shell", inline: <<-SHELL
    set -e
    sed -i".bak" -E "s@http://(us\.|)(archive|security)\.ubuntu\.com/ubuntu@http://ftp.jaist.ac.jp/pub/Linux/ubuntu@g" /etc/apt/sources.list
    ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
    apt-get -y update
    apt-get -y install git ansible

    rm -rf ansible-isucon
    git clone https://github.com/satoshun-example/ansible-isucon.git
    (
      cd ansible-isucon
      git checkout master
      cd isucon4-qualifier-ubuntu
      PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook playbook.yml -i local
    )
    rm -rf ansible-isucon
  SHELL
end
