# -*- mode: ruby -*-
# vi: set ft=ruby :

box = "ubuntu/wily64"

Vagrant.configure(2) do |config|
  config.vm.box = box

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 4
  end

  config.vm.synced_folder "webapp", "/home/isucon/webapp", owner: "vagrant", group: "vagrant"

  config.vm.provision "shell", inline: <<-SHELL
    set -e
    sed -i.bak -e "s@http://us\.archive\.ubuntu\.com/ubuntu/@mirror://mirrors.ubuntu.com/mirrors.txt@g" /etc/apt/sources.list
    export DEBIAN_FRONTEND=noninteractive

    apt-get update
    apt-get install -y ansible git

    rm -rf ansible-isucon
    git clone https://github.com/satoshun-example/ansible-isucon.git
    (
      cd ansible-isucon/isucon5-qualifier
      PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook -i local bench/ansible/playbook.yml
      PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook -i local image/ansible/playbook.yml
    )
    rm -rf ansible-isucon
  SHELL
end
